name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: forumapi
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm run migrate up
      - run: npm test
    env:
      HOST: localhost
      PORT: 5000
      PGHOST: localhost
      PGUSER: postgres
      PGDATABASE: forumapi
      PGPASSWORD: postgres
      PGPORT: 5432
      ACCESS_TOKEN_KEY: secret
      REFRESH_TOKEN_KEY: secret123
      ACCCESS_TOKEN_AGE: 3000
